# Modelling for Global Health - Data science in Python
## Day 2: Optimising code

If we get very large datasets, or need to computationally heavy tasks, how can we optimise our code? We will study two packages: [Numba](https://numba.pydata.org/) is the fundamental numeric computing and linear algebra package in Python, that allows for decent data analysis. We will learn it not only for the data analysis, but more importantly because it will be a package that will be always present in our `import` section as scientists. After NumPy we will go to [Dask](http://pandas.pydata.org/). Pandas is a dedicated data analysis package with a lot more functionalities than NumPy, making our life much easier in terms of data visualization and manipulation. All the power of Pandas will be completely unleashed in Section 5, where we will see how to visualize information in plots.

As usual, we begin importing the necessary packages

In [2]:
import numpy as np
import pandas as pd
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 1.21.2
Pandas: 1.3.1


## Numeric Python (NumPy)

NumPy is an open-source add-on module to Python that provides common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that
associated with common commercial software like MATLAB. The [NumPy](http://www.numpy.org/) (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. The main object NumPy works with is a *homogeneous multidimensional array*. Despite its intimidating name, these are nothing but tables of numbers, each labelled by a tuple of indices.

We will now explore some capabilities of NumPy that will prove very useful not only for data analyisis, but throughout all our life with Python.

### Creating Arrays

As mentioned before, the main object in NumPy is the *array*. Creating one is as easy as calling the command `array`

In [3]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

The same applies to multidimensional arrays

In [5]:
m = np.array([[[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])
m

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

There is one restriction with respect to the use of lists: while you could create lists with data of different type, all the data in an array has to be of the same type, and it will be converted automatically.

In [6]:
lst = [1., 'cat']
print(type(lst[0]))

arr = np.array(lst)
print(type(arr[0]))

<class 'float'>
<class 'numpy.str_'>


(We will go deeper into indexing in a while)

-----
A NumPy array has a number of dimensions (or *axes*). To obtain the number of axes and the size of each of them you use the command `shape`. For 2-dimensional arrays (matrices), the order corresponds to (rows, columns)

There are two different ways of calling the `shape` command, either with `np.shape(arr)` or `arr.shape`. This is not the only command that works in both formats, and we will be finding some more in our way.

In [7]:
print(x.shape)
print(np.shape(m))

(3,)
(2, 2, 3)


### Special Arrays

Now we review some built-in functions that create matrices commonly used. `ones` and `zeros` return arrays of given shape and type (default is float64), filled with ones or zeros, respectively.

In [8]:
array_zeros=np.zeros((3, 2))
array_ones=np.ones((3, 2, 4), dtype=np.int8)

In [9]:
array_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

`arange(begin, end, step)` returns evenly spaced values within a given interval. Note that the beginning point is included, but not the ending.

In [11]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
len(n)

15

**Exercise 1 **: Create an array of the first million of odd numbers, both with `arange` and using loops. Try timing both methods to see which one is faster. For that, use `%timeit`.

In [15]:
%timeit a = np.arange(1, 2e6, 2)

%timeit b = [i for i in range(2000000) if i % 2 == 1]


595 µs ± 6.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
135 ms ± 936 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
b = []
for i in range(2000000):
    if i % 2 == 1:
        b.append(i)

Similarly, `linspace(begin, end, points)` returns evenly spaced numbers over a specified interval. Here, instead of specifying the step, you specify the amount of points you want. Also with `linspace` you include the ending of the interval.

In [20]:
o = np.linspace(0, 30, 15)
o

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

In [18]:
len(o)

15

`reshape` changes the shape of an array, but not its data. This is another of the commands that can be called before or after the array.

In [21]:
print(n.reshape(3, 5))
np.reshape(n, (5, 3))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

Note however that, in order for these changes to be permanent, you should do a reassignment of the variable

In [22]:
print(n)  # After the reshapings above, the original array stays being the same

n = n.reshape(3, 5)
n   # Now that we have reassigned it is when it definitely changes shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining Arrays

The most general command for combining arrays is `concatenate(arrs, d)`. It takes a list of arrays and concatenates them along axis $d$

In [23]:
p = np.ones([2, 2, 2])
p

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
np.concatenate([p, 2 * p], 0)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [25]:
np.concatenate([p, 2 * p], 1)

array([[[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]],

       [[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]]])

In [26]:
np.concatenate([p, 2 * p], 2)

array([[[1., 1., 2., 2.],
        [1., 1., 2., 2.]],

       [[1., 1., 2., 2.],
        [1., 1., 2., 2.]]])

However, for common combinations there exist special commands. Use `vstack` to stack arrays in sequence vertically (row wise), `hstack` to stack arrays in sequence horizontally (column wise), and `block` to create arrays out of blocks (only available in versions 1.13.0+)

In [27]:
q = np.ones((2, 2))
np.vstack([q, 2 * q])

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.]])

In [29]:
np.hstack([q, 2 * q])

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.]])

In [30]:
np.block([[q, np.zeros((2, 2))], [np.zeros((2, 2)), 2 * q]])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 2., 2.],
       [0., 0., 2., 2.]])

### Operations

You can perform easily element-wise operations on arrays of any shape. Use the typical symbols, +, -, \*, / and \*\* to perform element-wise addition, subtraction, multiplication, division and power.

In [31]:
x = np.array([1, 2, 3])
print(x)
print(x + 10)
print(3 * x)
print(1 / x)
print(x ** (-2 / 3))
print(2 ** x)

[1 2 3]
[11 12 13]
[3 6 9]
[1.         0.5        0.33333333]
[1.         0.62996052 0.48074986]
[2 4 8]


Also (and obviously) these symbols can be used to operate between two arrays, which must be of the same shape. If this is the case, they also do element-wise operations

In [32]:
y = np.arange(4, 7, 1)
print(x + y)     # [1+4, 2+5, 3+6]
print(x * y)     # [1*4, 2*5, 3*6]
print(x / y)     # [1/4, 2/5, 3/6]
print(x ** y)    # [1**4, 2**5, 3**6]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


For doing vector or matrix multiplication, the command to be used is `dot`

In [33]:
x.dot(y) # 1*4 + 2*5 + 3*6

32

With python 3.5 matrix multiplication got it's own operator

In [34]:
x@y

32

In [36]:
X = np.array([[i + j for i in range(3, 6)] for j in range(3)])
Y = np.diag([1, 1], 1) + np.diag([1], -2)

print('{}\n'.format(X))
print(X * Y)
np.dot(X, Y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]

[[0 4 0]
 [0 0 6]
 [5 0 0]]


array([[5, 3, 4],
       [6, 4, 5],
       [7, 5, 6]])

**Exercise 2**: Take a 10x2 matrix representing $(x1,x2)$ coordinates and transform them into distance from the origin $(0,0)$.

*Hint 1: generate random numbers with the functions in numpy.random*

In [38]:
z = np.random.random((10, 2))
print(z)
x1, x2 = z[:, 0], z[:, 1]
R = np.sqrt(x1 ** 2 + x2 ** 2)
print(R)

[[0.49911368 0.13525048]
 [0.45445848 0.75578577]
 [0.35504442 0.89335571]
 [0.36993209 0.09078725]
 [0.90172549 0.59466673]
 [0.16026895 0.91580749]
 [0.50482964 0.22272297]
 [0.63294128 0.77223856]
 [0.13774436 0.15791853]
 [0.01852365 0.68784401]]
[0.51711426 0.88189832 0.96132251 0.38090954 1.08015618 0.9297255
 0.55177757 0.99848238 0.20955136 0.68809338]


#### Transposing

Transposition is a very important operation for linear algebra. Although NumPy is capable of correctly doing matrix-vector products correctly regardless of the orientation of the vector, it is not the case for products of matrices

In [41]:
Z = np.arange(0, 12, 1).reshape((4, 3))
print(Z)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 5 6]


In [42]:
np.dot(Z, y)

array([ 17,  62, 107, 152])

In [43]:
np.dot(Z, y.T)

array([ 17,  62, 107, 152])

In [47]:
Z.dot(X)
print(X)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [45]:
(Z.T).dot(X)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

#### Array Methods

To not have to go from NumPy arrays to lists back and forth, NumPy contains some functions to know properties of your arrays. Actually, there are more of these functions than in standard Python.

In [48]:
a = np.array([-4, -2, 1, 3, 5])
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

5
-4
3
0.6
3.2619012860600183


Some interesting functions are `argmax` and `argmin`, which return the index of the maximum and minimum values in the array.

In [49]:
print(a.argmax())
print(a.argmin())

4
0


### Indexing/Slicing

We have already seen briefly that to access individual elements you use the bracket notation: `array[ax_0, ax_1, ...]`, where the `ax_i` denotes the coordinate in the `i`-th axis. You can even use this to assign new values to your elements.

In [50]:
r = [4, 5, 6, 7]
print(r[2])
r[0] = 198
r

6


[198, 5, 6, 7]

To select a range of rows or columns you can use a colon :. A second : can be used to indicate the step size. `array[start:stop:stepsize]`. If you leave `start` (`stop`) blank, the selection will go from the very beginning (until the very end) of the array

In [51]:
s = np.arange(13)**2
print(s)
print(s[3:9])
print(s[2:10:3])
s[-5::-2]

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[ 9 16 25 36 49 64]
[ 4 25 64]


array([64, 36, 16,  4,  0])

The same applies to matrices or higher-dimensional arrays

In [52]:
r = np.arange(36).reshape((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

You can also select specific rows and columns, separated by commas

In [54]:
r[[1, 3, 4], 1:3]

array([[ 7,  8],
       [19, 20],
       [25, 26]])

A very useful tool is *conditional indexing*, where we apply a function, assignment... only to those elements of an array that satisfy some condition

In [58]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Exercise 3**: Create a random 1-dimensional array, and find which element is closest to 0.7

In [59]:
Z = np.random.uniform(0,1,100)
z = 0.7
m = Z[np.abs(Z - z).argmin()]
print(m)

0.6983069853094687


In [60]:
np.abs(Z - z).min()

0.0016930146905312915

#### Copying Data

**Be very careful with copying and modifying arrays in NumPy!** You will see the reason right now. Let's begin defining `r2` as a slice of r

In [61]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

And now let's set all its elements to zero

In [62]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

When looking at `r`, we see that it has also been changed!

In [63]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

The proper way of handling selections without modifying the original arrays is through the `copy` command.

In [64]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now we can safely modify `r_copy` without affecting `r`.

In [65]:
r_copy[:] = 10
print('{}\n'.format(r_copy))
r

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]



array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Iterating Over Arrays

Finally, you can iterate over arrays in the same way as you iterate over lists

In [66]:
test = np.random.randint(0, 10, (4,3))
test

array([[4, 1, 9],
       [9, 4, 5],
       [6, 1, 2],
       [2, 1, 1]])

You can iterate by row:

In [67]:
for row in test:
    print(row)

[4 1 9]
[9 4 5]
[6 1 2]
[2 1 1]


Or by row index

In [68]:
for i in range(len(test)):
    print(test[i])

[4 1 9]
[9 4 5]
[6 1 2]
[2 1 1]


Or by row and index:

In [69]:
for i, row in enumerate(test):
    print('Row {} is {}'.format(i, row))

Row 0 is [4 1 9]
Row 1 is [9 4 5]
Row 2 is [6 1 2]
Row 3 is [2 1 1]


In the same way as with lists, you can use `zip` to iterate over multiple iterables.

In [70]:
test2 = test**2
test2

array([[16,  1, 81],
       [81, 16, 25],
       [36,  1,  4],
       [ 4,  1,  1]])

In [71]:
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[4 1 9] + [16  1 81] = [20  2 90]
[9 4 5] + [81 16 25] = [90 20 30]
[6 1 2] + [36  1  4] = [42  2  6]
[2 1 1] + [4 1 1] = [6 2 2]


**Exercise 4**: Create a function that iterates over the columns of a 2-dimensional array

In [74]:
def iterate(inp):
    for i, row in enumerate(inp):
        print(i, row)

print(test)
iterate(test.T)

[[4 1 9]
 [9 4 5]
 [6 1 2]
 [2 1 1]]
0 [4 9 6 2]
1 [1 4 1 1]
2 [9 5 2 1]


### Loading and Saving Data

To load and save data NumPy has the `loadtxt` and `savetxt` commands. However, they only work for two-dimensional arrays

In [75]:
np.savetxt('numpytest.txt', test)
np.loadtxt('numpytest.txt')

array([[4., 1., 9.],
       [9., 4., 5.],
       [6., 1., 2.],
       [2., 1., 1.]])

## Pandas

When dealing with numeric matrices and vectors in Python, NumPy makes life a lot easier. For more complex data, however, it leaves a bit to be desired. For those used to working with dedicated languages like R, doing data analysis directly with numpy feels like a step back. Fortunately, some nice folks have written the Python Data Analysis Library (a.k.a. [pandas](http://pandas.pydata.org/)). Pandas provides an R-like DataFrame, produces high quality plots with matplotlib, and integrates nicely with other libraries that expect NumPy arrays.

Pandas works with `Series` of data, that then are arranged in `DataFrame`s. A dataframe will be the object closest to an Excel spreadsheet that you will see throughout the course (but of course, given that it is integrated in Python and can be combined with so many different packages, dataframes are much more powerful than Excel spreadsheets). The data in the series can be either qualitative or quantitative data. Creating a series is as easy as creating a NumPy array from a one-dimensional list.

In [76]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [77]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

Notice that the series is indexed by default by integers. You can change this indexing by using a dictionary instead of a list for creating the series.

In [78]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

On the other hand, `DataFrame`s can be built from two-dimensional arrays, with the ability of labelling columns and indexing the rows

In [79]:
u = pd.DataFrame(np.random.randn(1000,6), index=np.arange(0, 3000, 3), 
                 columns=['A', 'B', 'C', 'D', 'E', 'F'])
u

A         B         C         D         E         F
0     0.411216 -1.125631  1.144923  0.360671  1.299839 -2.304557
3    -0.104584 -0.275002  2.513509  0.262261  0.484080 -0.577940
6    -1.709117  0.309156  0.645219  0.362136 -1.582443  1.325490
9    -0.646869  0.820089 -0.121788 -1.182607  0.169760 -0.191547
12    1.274634  0.605899 -1.365210  0.743066 -0.335459  0.300962
...        ...       ...       ...       ...       ...       ...
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134  1.252217
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535 -0.416809
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029  0.851857
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -0.008958
2997 -1.657631  0.117647  0.171976  1.632397  0.940502 -0.053911

[1000 rows x 6 columns]

As you might have noticed, it is a bit ugly to deal with large dataframes. There are however some functions that allows to have an idea of the data in a frame.

In [80]:
u.head()

A         B         C         D         E         F
0   0.411216 -1.125631  1.144923  0.360671  1.299839 -2.304557
3  -0.104584 -0.275002  2.513509  0.262261  0.484080 -0.577940
6  -1.709117  0.309156  0.645219  0.362136 -1.582443  1.325490
9  -0.646869  0.820089 -0.121788 -1.182607  0.169760 -0.191547
12  1.274634  0.605899 -1.365210  0.743066 -0.335459  0.300962

In [81]:
u.tail()

A         B         C         D         E         F
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134  1.252217
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535 -0.416809
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029  0.851857
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -0.008958
2997 -1.657631  0.117647  0.171976  1.632397  0.940502 -0.053911

In [82]:
u.describe()

A            B            C            D            E  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     -0.010704    -0.025293    -0.033941    -0.002288     0.044878   
std       1.036826     1.018332     1.004480     0.985801     0.990983   
min      -3.227852    -3.615797    -3.166300    -3.312178    -3.049982   
25%      -0.695337    -0.698548    -0.706553    -0.660094    -0.601995   
50%      -0.017383    -0.012806    -0.040539    -0.008961     0.081967   
75%       0.680814     0.662942     0.596256     0.632166     0.674930   
max       3.424445     3.372802     3.098262     3.053989     2.776430   

                 F  
count  1000.000000  
mean      0.018516  
std       1.004436  
min      -3.655245  
25%      -0.618937  
50%      -0.003167  
75%       0.718158  
max       2.989418

### Indexing/Slicing in Pandas

The easiest way of accessing information in a Pandas dataframe, equivalent to the way used in NumPy, is using the `iloc` command. With this you can also set specific values, do conditional indexing... all that we have seen before in section 2.4

In [83]:
u.iloc[125:132,[0, 2, 5]]

A         C         F
375 -0.485594 -0.518961  1.492432
378 -3.022162 -1.515273 -0.770565
381  0.149452  0.287113 -0.334283
384 -0.223639 -0.000831 -0.537772
387  0.020571 -1.570409  0.185156
390 -1.300296  2.287708 -0.279852
393 -0.862555  0.447630  1.217457

However, there are a few different ways of accessing the data in a Pandas dataframe, that typically have a more "direct" connection with the actual content fo the dataframe. Individual or sets of columns can also be accessed by their column names. Choosing one single column will give a Series, while two or more will produce a Dataset

In [84]:
u['A'].head()

0     0.411216
3    -0.104584
6    -1.709117
9    -0.646869
12    1.274634
Name: A, dtype: float64

In [85]:
u[['A', 'D']].head()

A         D
0   0.411216  0.360671
3  -0.104584  0.262261
6  -1.709117  0.362136
9  -0.646869 -1.182607
12  1.274634  0.743066

Not only that, you can access a single column without the need of brackets []

In [86]:
u.A.head()

0     0.411216
3    -0.104584
6    -1.709117
9    -0.646869
12    1.274634
Name: A, dtype: float64

The usual [] will select specific rows according to the row number

In [87]:
u[0:10][list('BCF')]

B         C         F
0  -1.125631  1.144923 -2.304557
3  -0.275002  2.513509 -0.577940
6   0.309156  0.645219  1.325490
9   0.820089 -0.121788 -0.191547
12  0.605899 -1.365210  0.300962
15 -0.612926  1.139787  1.021581
18 -1.184174 -1.535477  0.782439
21  0.572855  0.007486 -0.693340
24 -0.240889  0.267571 -3.145057
27 -0.503256 -0.061491  0.210647

You can also choose specific rows according to their indices with the `loc` command

In [90]:
u.loc[6:15]

A         B         C         D         E         F
6  -1.709117  0.309156  0.645219  0.362136 -1.582443  1.325490
9  -0.646869  0.820089 -0.121788 -1.182607  0.169760 -0.191547
12  1.274634  0.605899 -1.365210  0.743066 -0.335459  0.300962
15 -0.721728 -0.612926  1.139787  0.329991  0.660282  1.021581

Or, you can access just the elements that satisfy some condition

In [91]:
u[u.D > 2]

A         B         C         D         E         F
72   -0.338482  0.225680  0.267424  2.234449  0.966637  0.253222
243   0.592281 -0.365087 -0.967662  2.473396  0.576809  2.130184
378  -3.022162  0.459158 -1.515273  2.340180  0.548856 -0.770565
525   0.888017 -1.151589  0.012688  2.057402 -0.799215  0.208907
873  -0.818732  1.664082 -0.636385  2.533360  1.752850 -0.771500
936  -0.872950  0.099281 -0.422253  2.593251  0.267335  0.284194
942  -1.733579  0.253967 -0.613147  2.521922  1.226781  0.037941
981  -0.107355 -0.304923  1.710283  2.165413  1.455118  1.889234
1341  0.267127  1.200105 -0.998348  2.846205 -1.145305  1.627145
1653 -0.446099  0.799753 -0.086620  3.053989 -1.274812  0.053008
1764  1.531940 -1.148065 -0.949762  2.727493  1.983646 -0.916439
1815 -1.383660 -1.342937 -0.256956  2.386595 -1.103081 -1.213627
1869 -1.362958 -0.474977  0.564300  2.153319  1.390451 -0.177079
1899 -2.025160  1.212708  1.090101  2.062773 -2.166144 -2.087103
1920 -1.375503 -0.308377  1.435353  2.188049 -0.585432  0.641405
2070  0.073924  1.424489  1.313878  2.271040  0.750965  0.541342
2163 -0.311241  2.179967  0.969478  2.363819 -1.308980  0.092688
2340 -0.824026 -0.830099 -0.842533  2.517308  1.410262  0.854382
2715 -0.165511 -1.265864  1.830793  2.570467 -0.473684 -0.551209
2775 -1.257902 -0.055800  0.038597  2.162830  0.089997  0.249271
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029  0.851857

In [92]:
u[~(u.D > 2)]  # For the inverse of u.D > 2

A         B         C         D         E         F
0     0.411216 -1.125631  1.144923  0.360671  1.299839 -2.304557
3    -0.104584 -0.275002  2.513509  0.262261  0.484080 -0.577940
6    -1.709117  0.309156  0.645219  0.362136 -1.582443  1.325490
9    -0.646869  0.820089 -0.121788 -1.182607  0.169760 -0.191547
12    1.274634  0.605899 -1.365210  0.743066 -0.335459  0.300962
...        ...       ...       ...       ...       ...       ...
2982  1.268347 -2.557879  0.195930  0.381675 -0.045897 -0.748257
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134  1.252217
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535 -0.416809
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -0.008958
2997 -1.657631  0.117647  0.171976  1.632397  0.940502 -0.053911

[979 rows x 6 columns]

### Computing With `DataFrames`

You can calculate with `DataFrames` or their columns (which are `Series`) the same way you could with `arrays`s

In [93]:
u['F'] = 1 / u['F']
u['F'].head()

0    -0.433923
3    -1.730283
6     0.754438
9    -5.220644
12    3.322680
Name: F, dtype: float64

In [94]:
np.mean(u)

A    -0.010704
B    -0.025293
C    -0.033941
D    -0.002288
E     0.044878
F   -12.015799
dtype: float64

You can apply functions to the whole dataset or specific columns with the `apply` command. `apply` acts on the whole column at a time (i.e. a Pandas `Series`), so you can compute things that depend on several values of the column, for instance the mean value. To apply functions in a real element-by-element basis the function `applymap` or `Series.apply` should be used.

In [95]:
def mn(col):
    return sum(col) / len(col)

u.apply(mn)

A    -0.010704
B    -0.025293
C    -0.033941
D    -0.002288
E     0.044878
F   -12.015799
dtype: float64

While most can be directly calculated (including the given example of the mean), `apply` also works on columns with strings or categorical data, where no mathematical operations are defined. The limit is the imagination.

### Combining `DataFrames`

Something we will do quite often as scientists is combining data from different sources into one single source. This can be achieved by different commands in Pandas, depending on the actual goal we want.

To begin with, appending new rows of data is achieved by the command `append`.

In [96]:
newdata = pd.DataFrame(np.ones((5, 6)), index=np.arange(3003, 3018, 3), columns=list('ABCDEF'))
newdata

A    B    C    D    E    F
3003  1.0  1.0  1.0  1.0  1.0  1.0
3006  1.0  1.0  1.0  1.0  1.0  1.0
3009  1.0  1.0  1.0  1.0  1.0  1.0
3012  1.0  1.0  1.0  1.0  1.0  1.0
3015  1.0  1.0  1.0  1.0  1.0  1.0

In [97]:
unew = u.append(newdata)
unew.tail(10)

A         B         C         D         E           F
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134    0.798584
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535   -2.399181
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029    1.173905
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -111.631950
2997 -1.657631  0.117647  0.171976  1.632397  0.940502  -18.549236
3003  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000

The same result can be obtained with `concat`.

In [98]:
pd.concat([u, newdata]).tail(10)

A         B         C         D         E           F
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134    0.798584
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535   -2.399181
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029    1.173905
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -111.631950
2997 -1.657631  0.117647  0.171976  1.632397  0.940502  -18.549236
3003  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3006  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3009  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3012  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000
3015  1.000000  1.000000  1.000000  1.000000  1.000000    1.000000

New columns of data can just be asigned or added with the command `join`.

In [99]:
u['G'] = np.random.choice(['a', 'b', 'c'], len(u))
u.tail()

A         B         C         D         E           F  G
2985 -0.670494 -0.342332  0.435097 -1.420804 -0.453134    0.798584  a
2988 -1.992404 -0.937323  0.576221 -1.831667  0.414535   -2.399181  b
2991 -1.409666  0.177457 -1.125919  2.362793  0.693029    1.173905  c
2994 -0.248026  1.246209  1.383035  1.121274  1.180247 -111.631950  a
2997 -1.657631  0.117647  0.171976  1.632397  0.940502  -18.549236  a

### Grouping Data

In [101]:
for h, group in u.groupby('G')

In [100]:
for h, group in u.groupby('G'):
    print('{}: {}'.format(h, np.mean(group['F'])))

a: -0.13291649597469382
b: -5.114983427226455
c: -31.345657615492946


In [ ]:
u.groupby('G').describe()

### Loading and saving dataframes

To load and save Pandas dataframes we will use the `to_csv` and `read_csv` commands

In [102]:
u.to_csv('test.csv')
v = pd.read_csv('test.csv', index_col=0)
v.head()

A         B         C         D         E         F  G
0   0.411216 -1.125631  1.144923  0.360671  1.299839 -0.433923  c
3  -0.104584 -0.275002  2.513509  0.262261  0.484080 -1.730283  c
6  -1.709117  0.309156  0.645219  0.362136 -1.582443  0.754438  c
9  -0.646869  0.820089 -0.121788 -1.182607  0.169760 -5.220644  b
12  1.274634  0.605899 -1.365210  0.743066 -0.335459  3.322680  c

But, as an addition, Pandas has special commands to load and save Excel spreadsheets (yay!). However, to use it you'll need the `openpyxl` and `xlrd` packages.

**Exercise 5**: Download [this dataset](https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv) and load it, using the first column as the index. Take a look at it, and do the following things:
- Choose the columns 'Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1' and 'Type2' 
- Create a function that lowercases strings and apply it to 'Type1' and 'Type2' (*Extra: just capitalize the strings, i.e., leave the first letter uppercase and lowercase the rest*)
- Create a function that returns a Boolean value (don't be afraif by this, it is a function that returns either True or False) that tells if a Pokémon has high stamina (BaseStamina>170) or not. Store this information in a new column and show the list of Pokémon with high stamina
- Show the instructor the last 15 rows of your dataset

In [104]:
df = pd.read_csv('https://raw.githubusercontent.com/ChihChengLiang/pokemongor/master/data-raw/pokemons.csv', 
                 index_col=0)

df = df[['Identifier', 'BaseStamina', 'BaseAttack', 'BaseDefense', 'Type1', 'Type2']]

capitalize = lambda st: st.capitalize()

for col in ['Type1', 'Type2']:
    df[col] = df[col].apply(capitalize)
    
def highstamina(x):
    return True if x > 170 else False

df['HighStamina'] = df.BaseStamina.apply(highstamina)

print(df[df['HighStamina'] == True].Identifier)

df['DifHighStamina'] = df.BaseStamina > 170

df.tail(15)

PkMn
31      Nidoqueen
36       Clefable
39     Jigglypuff
40     Wigglytuff
59       Arcanine
62      Poliwrath
68        Machamp
79       Slowpoke
80        Slowbro
87        Dewgong
89            Muk
103     Exeggutor
108     Lickitung
112        Rhydon
113       Chansey
115    Kangaskhan
130      Gyarados
131        Lapras
134      Vaporeon
143       Snorlax
144      Articuno
145        Zapdos
146       Moltres
149     Dragonite
150        Mewtwo
151           Mew
Name: Identifier, dtype: object


Identifier  BaseStamina  BaseAttack  BaseDefense     Type1   Type2  \
PkMn                                                                       
137      Porygon          130         156          158    Normal    None   
138      Omanyte           70         132          160      Rock   Water   
139      Omastar          140         180          202      Rock   Water   
140       Kabuto           60         148          142      Rock   Water   
141     Kabutops          120         190          190      Rock   Water   
142   Aerodactyl          160         182          162      Rock  Flying   
143      Snorlax          320         180          180    Normal    None   
144     Articuno          180         198          242       Ice  Flying   
145       Zapdos          180         232          194  Electric  Flying   
146      Moltres          180         242          194      Fire  Flying   
147      Dratini           82         128          110    Dragon    None   
148    Dragonair          122         170          152    Dragon    None   
149    Dragonite          182         250          212    Dragon  Flying   
150       Mewtwo          212         284          202   Psychic    None   
151          Mew          200         220          220   Psychic    None   

      HighStamina  DifHighStamina  
PkMn                               
137         False           False  
138         False           False  
139         False           False  
140         False           False  
141         False           False  
142         False           False  
143          True            True  
144          True            True  
145          True            True  
146          True            True  
147         False           False  
148         False           False  
149          True            True  
150          True            True  
151          True            True